spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456


  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    servlet:
      content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
    max-http-form-post-size: 15360

location:
  img: D:\Images\
  imgPath: /Images/
  #img: /home/liuleilei/scanner/images/
  audio: D:\Audio\
